CREATE TABLE IF NOT EXISTS public.users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.items (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name VARCHAR(255) NOT NULL,
	description VARCHAR NOT NULL,
	available BOOLEAN DEFAULT false NOT NULL,
	owner_id BIGINT NOT NULL,
	request_id BIGINT NULL,
	CONSTRAINT items_pk PRIMARY KEY (id),
	CONSTRAINT item_owner_fk FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS public.bookings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    status VARCHAR(10) DEFAULT 'WAITING' NOT NULL,
	CONSTRAINT bookings_pk PRIMARY KEY (id),
    CONSTRAINT bookings_item_fk FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT bookings_booker_fk FOREIGN KEY (booker_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(512) NOT NULL,
  item_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  create_date TIMESTAMP,
  CONSTRAINT comments_pk PRIMARY KEY (id),
  CONSTRAINT comments_author_fk FOREIGN KEY (author_id) REFERENCES users(id),
  CONSTRAINT comments_item_fk FOREIGN KEY (item_id) REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS public.requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(512) NOT NULL,
  requestor_id BIGINT NOT NULL,
  create_date TIMESTAMP,
  CONSTRAINT requests_pk PRIMARY KEY (id),
  CONSTRAINT requests_user_fk FOREIGN KEY (requestor_id) REFERENCES users(id)
);
